

services:
  cifrario:
    build:  
      context: .  
      dockerfile: Dockerfile
    container_name: cifrario-container 
    volumes:
      - ./Cifrario:/app/Cifrario  
    working_dir: /app  
    command: java -jar /root/.m2/repository/org/esame/Cifrario/1.0-SNAPSHOT/Cifrario-1.0-SNAPSHOT.jar.jar