

services:
  cifrario:
    build:  
      context: .  
      dockerfile: Dockerfile
    container_name: cifrario-container 
    volumes:
      - ./Cifrario:/app/Cifrario  
    working_dir: /app  
    command: java -jar /app/Cifrario/target/Cifrario-1.0-SNAPSHOT.jar